# Generated by Django 4.0.3 on 2022-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupEWC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=122)),
                ('d_email', models.CharField(max_length=122)),
                ('d_password', models.CharField(max_length=122)),
                ('d_rpassword', models.CharField(max_length=122)),
            ],
        ),
    ]
